from parameters import OTHER_POWER_ITEMS, SOURCES
from parameters import ETA_CHARGE, ETA_DISCHARGE
from utility import PowerData
import numpy as np


def simulate_surplus(power_in: PowerData, max_capacity: float, k_pv: float, k_w: float) -> PowerData:
    """
    Simulate the production of electricity, starting from the production data by source, the electric power generation using:
    - an increased storage capacity max_capacity (GWh) - through electrochemical batteries or pumped storage - to store surplus energy and release it when needed
    - an increased photovoltaic power, by a factor k_pv relative to the current production,
    - an increased wind power, by a factor k_w relative to the current production.
    The simulation returns a dictionary with the updated electric power generation.

    Parameters
    ---------
    power_in : PowerData
        Current electric power data, divided by type (for each quarter hour, in GW).
    max_capacity : float
        Maximum storage capacity, in GWh.
    k_pv : float
        Factor by which to increase the photovoltaic power.
    k_w : float
        Factor by which to increase the wind power.

    Returns
    ----------
    dict[str, np.ndarray]
        Updated electric power generation (for each quarter hour, in GW).
    """
    new_power_item: dict[str, np.ndarray] = {} # Dizionario per la produzione simulata
    N_INTERVALS = len(power_in.power_item["Photovoltaic"]) # Numero di intervalli temporali (quarti d'ora) nella simulazione
    for source in SOURCES + OTHER_POWER_ITEMS:
        if source in power_in.power_item:
            new_power_item[source] = power_in.power_item[source].copy()
        else:
            new_power_item[source] = np.zeros(N_INTERVALS)

    # Simulation of the electricity production with surplus from photovoltaic, wind and storage
    capacity = max_capacity # Initialize the storage with maximum capacity, max_capacity (GWh)
    for t in range(N_INTERVALS):
        new_power_item["Photovoltaic"][t] = k_pv * power_in.power_item["Photovoltaic"][t]  # Update the photovoltaic production with the surplus
        new_power_item["Wind"][t] = k_w * power_in.power_item["Wind"][t]  # Update the wind production with the surplus
        photovoltaic_surplus = power_in.power_item["Photovoltaic"][t] * (k_pv - 1)  # Photovoltaic surplus due to the factor k
        wind_surplus = power_in.power_item["Wind"][t] * (k_w - 1)  # Wind surplus due to the factor k
        surplus = photovoltaic_surplus + wind_surplus  # Total surplus of available electric energy
        if surplus > power_in.power_item["Thermal"][t]:
            new_power_item["Thermal"][t] = 0 # Set the thermal production to 0
            surplus -= power_in.power_item["Thermal"][t]  # Reduce the total surplus of the thermal production
        else:
            new_power_item["Thermal"][t] -= surplus  # Reduce the thermal production due to the surplus
            surplus = 0  # No more surplus available
        if surplus > power_in.power_item["Import"][t]:
            new_power_item["Import"][t] = 0 # Set the importation to 0 due to the surplus
            new_power_item["Net Import"][t] = -power_in.power_item["Export"][t] # Update the net importation
            surplus -= power_in.power_item["Import"][t]  # Reduce the total surplus of the importation
        else:
            new_power_item["Import"][t] -= surplus  # Reduce the importation due to the surplus
            new_power_item["Net Import"][t] -= surplus  # Reduce the net importation due to the surplus
            surplus = 0  # No more surplus available
        capacity += surplus / 4 * ETA_CHARGE  # Charge the storage considering the charging efficiency
        if capacity > max_capacity:
            capacity = max_capacity  # Limit the state of the storage to the maximum capacity (curtailment)
        if capacity > 0:
            charge = min(capacity * 4 * ETA_DISCHARGE, new_power_item["Thermal"][t])  # Calculate the power that the storage is able to generate
            new_power_item["Storage"][t] += charge  # Increase the power generated by the storage by the same amount
            new_power_item["Thermal"][t] -= charge  # Reduce the thermal power by the same amount
            capacity -= charge / 4 / ETA_DISCHARGE  # Discharge the storage considering the discharging efficiency
        if capacity > 0:
            charge = min(capacity * 4 * ETA_DISCHARGE, new_power_item["Import"][t])  # Calculate the power that the storage is able to generate
            new_power_item["Storage"][t] += charge  # Increase the power generated by the storage by the same amount
            new_power_item["Import"][t] -= charge  # Reduce the importation by the same amount
            new_power_item["Net Import"][t] -= charge # Reduce the net importation by the same amount
            capacity -= charge / 4 / ETA_DISCHARGE  # Discharge the storage considering the discharging efficiency

    return PowerData(power_item=new_power_item, start=power_in.start, freq=power_in.freq)
    