import pandas as pd

from parameters import ETA_CHARGE, ETA_DISCHARGE, NUCLEAR_BASE_LOAD_FACTOR
from parameters import SOURCES, OTHER_POWER_ITEMS, SOURCE_COSTS
from utility import PowerData, EnergyData
from utility import compute_peaks, to_energy
import numpy as np

import utility

def simulate_power_redistribution(
        power_item: dict[str, float],
        capacity: float,
        max_capacity: float,
        k_pv: float,
        k_w: float,
        nuke: bool) -> tuple[dict[str, float], float]:
    """
    Starting from the production data by source, simulate the redistribution of electricity production
    at a given 15 minutes interval, assuming that the electricity production can be redistributed by:
    - a given amount of energy stored, available for discharge (GWh)
    - a given amount of energy storing capacity (GWh), available to store surplus energy
    - a given multiplicative factor for the photovoltaic and wind power production, to simulate an increase in the production of these sources
    - an optional nuclear power production, which can be included or excluded from the simulation.
    The simulation assumes that the surplus energy is used to reduce the thermal and importation production,
    and returns a dictionary with the updated electric power generation and the updated storage capacity.

    Parameters
    ---------
    power_item : dict[str, float]
        Current electric power data, for the given quarter hour, (in GW).
    capacity : float
        Current amount of energy stored, available for discharge (GWh).
    max_capacity : float
        Maximum storage capacity, in GWh.
    k_pv : float
        Factor by which to increase the photovoltaic power.
    k_w : float
        Factor by which to increase the wind power.
    nuke : bool
        Whether to include nuclear power production.

    Returns
    -------
    tuple[dict[str, float], float]
        Updated electric power generation (for each quarter hour, in GW) and the updated storage capacity (GWh).
    """
    new_power_item: dict[str, float] = {} # Dictionary for the simulated production
    for source in SOURCES + OTHER_POWER_ITEMS:
        if source in power_item.keys():
            new_power_item[source] = power_item[source]
        else:
            new_power_item[source] = 0.0

    new_power_item["Photovoltaic"] = k_pv * power_item["Photovoltaic"]  # Update the photovoltaic production with the surplus
    new_power_item["Wind"] = k_w * power_item["Wind"]  # Update the wind production with the surplus
    photovoltaic_surplus = power_item["Photovoltaic"] * (k_pv - 1)  # Photovoltaic surplus due to the factor k
    wind_surplus = power_item["Wind"] * (k_w - 1)  # Wind surplus due to the factor k
    surplus = photovoltaic_surplus + wind_surplus  # Total surplus of available electric energy
    if surplus > power_item["Thermal"]:
        new_power_item["Thermal"] = 0 # Set the thermal production to 0
        surplus -= power_item["Thermal"]  # Reduce the total surplus of the thermal production
    else:
        new_power_item["Thermal"] -= surplus  # Reduce the thermal production due to the surplus
        surplus = 0  # No more surplus available
    if surplus > power_item["Import"]:
        new_power_item["Import"] = 0 # Set the importation to 0 due to the surplus
        new_power_item["Net Import"] = -power_item["Export"] # Update the net importation
        surplus -= power_item["Import"]  # Reduce the total surplus of the importation
    else:
        new_power_item["Import"] -= surplus  # Reduce the importation due to the surplus
        new_power_item["Net Import"] -= surplus  # Reduce the net importation due to the surplus
        surplus = 0  # No more surplus available
    capacity += surplus / 4 * ETA_CHARGE  # Charge the storage considering the charging efficiency
    if capacity > max_capacity:
        capacity = max_capacity  # Limit the state of the storage to the maximum capacity (curtailment)
    if capacity > 0:
        charge = min(capacity * 4 * ETA_DISCHARGE, new_power_item["Thermal"])  # Calculate the power that the storage is able to generate
        new_power_item["Storage"] += charge  # Increase the power generated by the storage by the same amount
        new_power_item["Thermal"] -= charge  # Reduce the thermal power by the same amount
        capacity -= charge / 4 / ETA_DISCHARGE  # Discharge the storage considering the discharging efficiency
    if capacity > 0:
        charge = min(capacity * 4 * ETA_DISCHARGE, new_power_item["Import"])  # Calculate the power that the storage is able to generate
        new_power_item["Storage"] += charge  # Increase the power generated by the storage by the same amount
        new_power_item["Import"] -= charge  # Reduce the importation by the same amount
        new_power_item["Net Import"] -= charge # Reduce the net importation by the same amount
        capacity -= charge / 4 / ETA_DISCHARGE  # Discharge the storage considering the discharging efficiency
    if nuke:
        new_power_item["Nuclear"] = new_power_item["Thermal"]  # Update the nuclear production with the thermal production, as it is now included in the nuclear production
        new_power_item["Thermal"] = 0  # Set the thermal production to 0, as it is now included in the nuclear production
    return (new_power_item, capacity)

def compute_differential_costs(data1: EnergyData, data2: EnergyData) -> dict[dict[str, float]]:
    """
    Compute the differential costs between two energy data sets, considering the costs of each source.
    The function returns a dictionary with the differential costs for each source and the total differential cost.

    Parameters
    ---------
    data1 : EnergyData
        First energy data set, containing the energy produced by each source (in GWh).
    data2 : EnergyData
        Second energy data set, containing the energy produced by each source (in GWh).

    Returns
    -------
    dict[dict[str, float]]
        Dictionary with the differential costs for each source and the total differential cost.
    """
    differential_costs: dict[str, float] = {}
    total_cost = 0.0
    for source in SOURCE_COSTS:
        diff = 0.0
        if source in data1.energy_item:
            diff -= data1.energy_item[source][1]
        if source in data2.energy_item:
            diff += data2.energy_item[source][1]
        differential_costs[source] = diff
        total_cost += diff
    differential_costs["Total"] = total_cost
    return differential_costs

def simulate_alternative_scenario(power_in: PowerData, max_capacity: float, k_pv: float, k_w: float, nuke: bool) -> tuple[PowerData, EnergyData]:
    """
    Simulate the production of electricity, starting from the production data by source, the electric power generation using:
    - an increased storage capacity max_capacity (GWh) - through electrochemical batteries or pumped storage - to store surplus energy and release it when needed
    - an increased photovoltaic power, by a factor k_pv relative to the current production,
    - an increased wind power, by a factor k_w relative to the current production,
    - an optional nuclear power production, which can be included or excluded from the simulation.
    The simulation returns a dictionary with the updated electric power generation.

    Parameters
    ---------
    power_in : PowerData
        Current electric power data, divided by type (for each quarter hour, in GW).
    max_capacity : float
        Maximum storage capacity, in GWh.
    k_pv : float
        Factor by which to increase the photovoltaic power.
    k_w : float
        Factor by which to increase the wind power.
    nuke : bool
        Whether to include nuclear power in the simulation.

    Returns
    ----------
    tuple[PowerData, EnergyData]
        Updated electric power generation (for each quarter hour, in GW) and corresponding energy data.
    """
    new_power_item: dict[str, np.ndarray] = {} # Dizionario per la produzione simulata
    N_INTERVALS = len(power_in.power_item["Photovoltaic"]) # Numero di intervalli temporali (quarti d'ora) nella simulazione
    for source in SOURCES + OTHER_POWER_ITEMS:
        if source in power_in.power_item:
            new_power_item[source] = power_in.power_item[source].copy()
        else:
            new_power_item[source] = np.zeros(N_INTERVALS)

    # Simulation of the electricity production with surplus from photovoltaic, wind and storage
    capacity = max_capacity # Initialize the storage with maximum capacity, max_capacity (GWh)
    for t in range(N_INTERVALS):
        reference_power_item_at_t: dict[str, float] = {}  # Dictionary for the reference production at time t
        for source in SOURCES + OTHER_POWER_ITEMS:
            if source in power_in.power_item:
                reference_power_item_at_t[source] = power_in.power_item[source][t]
        new_power_item_at_t, capacity = simulate_power_redistribution(
            reference_power_item_at_t,
            capacity,
            max_capacity,
            k_pv,
            k_w,
            nuke
        )
        for source in SOURCES + OTHER_POWER_ITEMS:  # Convert the lists to numpy arrays
            new_power_item[source][t] = new_power_item_at_t[source]

    if nuke:
        nuclear_base_load = np.max(new_power_item["Nuclear"]) * NUCLEAR_BASE_LOAD_FACTOR  # Nuclear base load, assumed to be NUCLEAR_BASE_LOAD_FACTOR of the peak power
        for t in range(N_INTERVALS):
            if new_power_item["Nuclear"][t] < nuclear_base_load:
                nuclear_surplus = nuclear_base_load - new_power_item["Nuclear"][t]  # Surplus of nuclear production to reach the base load
                new_power_item["Nuclear"][t] = nuclear_base_load  # Set the nuclear production to the base load
                if new_power_item["Storage"][t] >= nuclear_surplus:
                    new_power_item["Storage"][t] -= nuclear_surplus  # Reduce the storage by the nuclear surplus
                    capacity += nuclear_surplus / 4 / ETA_DISCHARGE  # Increase the storage capacity by the nuclear surplus
                else:
                    nuclear_surplus -= new_power_item["Storage"][t]  # Reduce the nuclear surplus by the storage
                    capacity += new_power_item["Storage"][t] / 4 / ETA_DISCHARGE  # Increase the storage capacity by the storage
                    new_power_item["Storage"][t] = 0  # Set the storage to 0
                new_power_item["Import"][t] -= nuclear_surplus  # Reduce the importation due to the nuclear surplus
                if new_power_item["Import"][t] < 0:
                    new_power_item["Import"][t] = 0  # Set the importation to 0 if it is negative
                new_power_item["Net Import"][t] = new_power_item["Import"][t] - new_power_item["Export"][t]  # Update the net importation

    power_after = PowerData(power_item=new_power_item, start=power_in.start, end=power_in.end)
    compute_peaks(power_after)  # Compute the peaks of the simulated power data
    return (power_after, to_energy(power_after))  # Return the simulated power data and the corresponding energy data

def decarbonization_feasibility(power_in: PowerData, max_capacity: float, k_pv: float, k_w: float) -> bool:
    """
    Check if, starting from the production data by source, it is possible to decarbonize the electricity production
    without recourse to nuclear power, just using:
    - an increased storage capacity max_capacity (GWh) - through electrochemical batteries or pumped storage - to store surplus energy and release it when needed
    - an increased photovoltaic power, by a factor k_pv relative to the current production,
    - an increased wind power, by a factor k_w relative to the current production.
    The simulation returns True if it is possible to decarbonize the electricity production, False otherwise.

    Parameters
    ---------
    power_in : PowerData
        Current electric power data, divided by type (for each quarter hour, in GW).
    max_capacity : float
        Maximum storage capacity, in GWh.
    k_pv : float
        Factor by which to increase photovoltaic power.
    k_w : float
        Factor by which to increase wind power.

    Returns
    -------
    bool
        True if it is possible to decarbonize the electricity production, False otherwise.
    """
    simulated_power, _ = simulate_alternative_scenario(power_in, max_capacity, k_pv, k_w, nuke=False)
    for t in range(len(simulated_power.power_item["Photovoltaic"])):
        if simulated_power.power_item["Thermal"][t] > 0 or simulated_power.power_item["Import"][t] > 0:
            return False
    return True

def compute_decarbonization_minimum_storage_capacity(
        power_in: PowerData,
        capacity_range: float,
        k_pv: float,
        k_w: float) -> float:
    """
    Compute the minimum storage capacity (GWh) needed to decarbonize the electricity production,
    starting from the production data by source, just using:
    - an increased photovoltaic power, by a factor k_pv relative to the current production,
    - an increased wind power, by a factor k_w relative to the current production.
    The simulation returns the minimum storage capacity needed to decarbonize the electricity production.

    Parameters
    ---------
    power_in : PowerData
        Current electric power data, divided by type (for each quarter hour, in GW).
    capacity_range : float
        Range of values to be checked, in storage capacity (GWh), within which to find the minimum capacity needed to decarbonize.
    k_pv : float
        Factor by which to increase photovoltaic power.
    k_w : float
        Factor by which to increase wind power.

    Returns
    -------
    float
        Minimum storage capacity (GWh) needed to decarbonize the electricity production.
        If it is not possible to decarbonize with the given max_capacity and capacity_res, returns -1.0.
    """
    # If it is not possible to decarbonize with the given max_capacity return -1.0
    if not decarbonization_feasibility(power_in, capacity_range, k_pv, k_w):
        return -1.0
    # Proceed by bisection to find the minimum storage capacity needed to decarbonize
    low_capacity = 0.0
    high_capacity = capacity_range
    capacity_res = capacity_range / 100.0  # Resolution of the storage capacity (GWh) within which to find the minimum capacity needed to decarbonize
    while high_capacity - low_capacity > capacity_res:
        current_capacity = (low_capacity + high_capacity) / 2
        feasible = decarbonization_feasibility(power_in, current_capacity, k_pv, k_w)
        if feasible:
            high_capacity = current_capacity
        else:
            low_capacity = current_capacity
    if high_capacity < capacity_range:
        return high_capacity
    return -1.0

def compute_decarbonization_map(
        power_in: PowerData,
        k_pv_range: float,
        k_w_range: float,
        capacity_range: float) -> list[tuple[float, float, float, float]]:
    """
    Compute the map of states in the k_pv-k_wind space, where decarbonizing the electricity production is possible
    without recourse to nuclear power. The simulation returns a list of tuples with:
    - the factor k_pv,
    - the factor k_wind,
    - the storage capacity (GWh),
    - the corresponding costs (G€/year),
    needed to decarbonize the electricity production.

    Parameters
    ----------
    power_in : PowerData
        Current electric power data, divided by type (for each quarter hour, in GW).
    k_pv_range : float
        Range of values to be checked, in the photovoltaic factor.
    k_w_range : float
        Range of values to be checked, in the wind power factor.
    capacity_range : float
        Range of values to be checked, in storage capacity space (GWh).

    Returns
    -------
    list[tuple[float, float, float, float]]
        List of tuples with:
        - factor k_pv,
        - factor k_wind,
        - storage capacity (GWh),
        - corresponding costs (G€/year)
        to decarbonize the electricity production without nuclear power.
    """
    results: list[tuple[float, float, float, float]] = []
    k_pv_step = k_pv_range / 10.0  # Step size for the k_pv factor
    k_w_step = k_w_range / 10.0  # Step size for the k_w factor
    k_pv = k_pv_range
    while k_pv >= 1.0:
        k_w = k_w_range
        while k_w >= 1.0:
            capacity = compute_decarbonization_minimum_storage_capacity(power_in, capacity_range, k_pv, k_w)
            if capacity < 0.0:
                break
            scenario = simulate_alternative_scenario(power_in, capacity, k_pv, k_w, nuke=False)
            costs = compute_differential_costs(utility.to_energy(power_in), scenario[1])["Total"]
            results.append((k_pv, k_w, capacity, costs))
            k_w -= k_w_step
        k_pv -= k_pv_step
    return results