from turtle import pd

from parameters import ETA_CHARGE, ETA_DISCHARGE, NUCLEAR_BASE_LOAD_FACTOR
from parameters import SOURCES, OTHER_POWER_ITEMS, SOURCE_COSTS
from utility import PowerData, EnergyData, CostData
from utility import compute_peaks, to_energy
import numpy as np


def simulate_alternative_scenario(power_in: PowerData, max_capacity: float, k_pv: float, k_w: float, nuke: bool) -> tuple[PowerData, EnergyData]:
    """
    Simulate the production of electricity, starting from the production data by source, the electric power generation using:
    - an increased storage capacity max_capacity (GWh) - through electrochemical batteries or pumped storage - to store surplus energy and release it when needed
    - an increased photovoltaic power, by a factor k_pv relative to the current production,
    - an increased wind power, by a factor k_w relative to the current production,
    - an optional nuclear power production, which can be included or excluded from the simulation.
    The simulation returns a dictionary with the updated electric power generation.

    Parameters
    ---------
    power_in : PowerData
        Current electric power data, divided by type (for each quarter hour, in GW).
    max_capacity : float
        Maximum storage capacity, in GWh.
    k_pv : float
        Factor by which to increase the photovoltaic power.
    k_w : float
        Factor by which to increase the wind power.
    nuke : bool
        Whether to include nuclear power in the simulation.

    Returns
    ----------
    tuple[PowerData, EnergyData]
        Updated electric power generation (for each quarter hour, in GW) and corresponding energy data.
    """
    new_power_item: dict[str, np.ndarray] = {} # Dizionario per la produzione simulata
    N_INTERVALS = len(power_in.power_item["Photovoltaic"]) # Numero di intervalli temporali (quarti d'ora) nella simulazione
    for source in SOURCES + OTHER_POWER_ITEMS:
        if source in power_in.power_item:
            new_power_item[source] = power_in.power_item[source].copy()
        else:
            new_power_item[source] = np.zeros(N_INTERVALS)

    # Simulation of the electricity production with surplus from photovoltaic, wind and storage
    capacity = max_capacity # Initialize the storage with maximum capacity, max_capacity (GWh)
    for t in range(N_INTERVALS):
        new_power_item["Photovoltaic"][t] = k_pv * power_in.power_item["Photovoltaic"][t]  # Update the photovoltaic production with the surplus
        new_power_item["Wind"][t] = k_w * power_in.power_item["Wind"][t]  # Update the wind production with the surplus
        photovoltaic_surplus = power_in.power_item["Photovoltaic"][t] * (k_pv - 1)  # Photovoltaic surplus due to the factor k
        wind_surplus = power_in.power_item["Wind"][t] * (k_w - 1)  # Wind surplus due to the factor k
        surplus = photovoltaic_surplus + wind_surplus  # Total surplus of available electric energy
        if surplus > power_in.power_item["Thermal"][t]:
            new_power_item["Thermal"][t] = 0 # Set the thermal production to 0
            surplus -= power_in.power_item["Thermal"][t]  # Reduce the total surplus of the thermal production
        else:
            new_power_item["Thermal"][t] -= surplus  # Reduce the thermal production due to the surplus
            surplus = 0  # No more surplus available
        if surplus > power_in.power_item["Import"][t]:
            new_power_item["Import"][t] = 0 # Set the importation to 0 due to the surplus
            new_power_item["Net Import"][t] = -power_in.power_item["Export"][t] # Update the net importation
            surplus -= power_in.power_item["Import"][t]  # Reduce the total surplus of the importation
        else:
            new_power_item["Import"][t] -= surplus  # Reduce the importation due to the surplus
            new_power_item["Net Import"][t] -= surplus  # Reduce the net importation due to the surplus
            surplus = 0  # No more surplus available
        capacity += surplus / 4 * ETA_CHARGE  # Charge the storage considering the charging efficiency
        if capacity > max_capacity:
            capacity = max_capacity  # Limit the state of the storage to the maximum capacity (curtailment)
        if capacity > 0:
            charge = min(capacity * 4 * ETA_DISCHARGE, new_power_item["Thermal"][t])  # Calculate the power that the storage is able to generate
            new_power_item["Storage"][t] += charge  # Increase the power generated by the storage by the same amount
            new_power_item["Thermal"][t] -= charge  # Reduce the thermal power by the same amount
            capacity -= charge / 4 / ETA_DISCHARGE  # Discharge the storage considering the discharging efficiency
        if capacity > 0:
            charge = min(capacity * 4 * ETA_DISCHARGE, new_power_item["Import"][t])  # Calculate the power that the storage is able to generate
            new_power_item["Storage"][t] += charge  # Increase the power generated by the storage by the same amount
            new_power_item["Import"][t] -= charge  # Reduce the importation by the same amount
            new_power_item["Net Import"][t] -= charge # Reduce the net importation by the same amount
            capacity -= charge / 4 / ETA_DISCHARGE  # Discharge the storage considering the discharging efficiency
        if nuke:
            new_power_item["Nuclear"][t] = new_power_item["Thermal"][t]  # Update the nuclear production with the thermal production, as it is now included in the nuclear production
            new_power_item["Thermal"][t] = 0  # Set the thermal production to 0, as it is now included in the nuclear production

    if nuke:
        nuclear_base_load = np.max(new_power_item["Nuclear"]) * NUCLEAR_BASE_LOAD_FACTOR  # Nuclear base load, assumed to be NUCLEAR_BASE_LOAD_FACTOR of the peak power
        for t in range(N_INTERVALS):
            if new_power_item["Nuclear"][t] < nuclear_base_load:
                nuclear_surplus = nuclear_base_load - new_power_item["Nuclear"][t]  # Surplus of nuclear production to reach the base load
                new_power_item["Nuclear"][t] = nuclear_base_load  # Set the nuclear production to the base load
                if new_power_item["Storage"][t] >= nuclear_surplus:
                    new_power_item["Storage"][t] -= nuclear_surplus  # Reduce the storage by the nuclear surplus
                    capacity += nuclear_surplus / 4 / ETA_DISCHARGE  # Increase the storage capacity by the nuclear surplus
                else:
                    nuclear_surplus -= new_power_item["Storage"][t]  # Reduce the nuclear surplus by the storage
                    capacity += new_power_item["Storage"][t] / 4 / ETA_DISCHARGE  # Increase the storage capacity by the storage
                    new_power_item["Storage"][t] = 0  # Set the storage to 0
                new_power_item["Import"][t] -= nuclear_surplus  # Reduce the importation due to the nuclear surplus
                if new_power_item["Import"][t] < 0:
                    new_power_item["Import"][t] = 0  # Set the importation to 0 if it is negative
                new_power_item["Net Import"][t] = new_power_item["Import"][t] - new_power_item["Export"][t]  # Update the net importation

    power_after = PowerData(power_item=new_power_item, start=power_in.start, end=power_in.end)
    compute_peaks(power_after)  # Compute the peaks of the simulated power data
    return (power_after, to_energy(power_after))  # Return the simulated power data and the corresponding energy data
    

def simulate_costs(energy_before: EnergyData, energy_after: EnergyData) -> CostData:
    """
    Simulate the costs of electricity production before and after the simulation, based on the energy data provided.
    Parameters
    ---------
    energy_before : EnergyData
        Current energy data, divided by type (for each quarter hour, in MWh).
    energy_after : EnergyData
        Energy data after the simulation, divided by type (for each quarter hour, in MWh).

    Returns
    ----------
    CostData
        Data structure containing the simulated costs.
    """
    annual_costs = CostData()
    energy_after.duration = energy_after.duration if energy_after.duration.days > 0 else pd.Timedelta(days=1)  # Avoid division by zero
    # Reparametrization factor to convert the costs to a solar year, based on the duration of the simulation, in hours
    k_year = 365 / energy_after.duration.days
    # Calculate the total costs for each source and store them in the CostData object
    for source in SOURCE_COSTS.keys():
        cost_after = 0
        if source in energy_after.energy_item:
            cost_after = energy_after.energy_item[source] * SOURCE_COSTS[source]
        cost_before = 0
        if source in energy_before.energy_item:
            cost_before = energy_before.energy_item[source] * SOURCE_COSTS[source]
        annual_costs.cost_item[source] = (cost_after - cost_before) * k_year * 1e-6  # Convert the costs to billions of dollars per year
    return annual_costs